#!/bin/bash

if [ -z "$PYFILE" ]; then
	echo "Error: Environment variable \$PYFILE not set."
	exit 1
fi

output_file="${PYFILE}c"

python -m py_compile "$PYFILE" && mv "__pycache__/${output_file}" . && rmdir "__pycache__"
